config/routes.rb
Rails.application.routes.draw do
  root to: 'groups#my_groups'

  resources :prayers do
    get "my_prayers", on: :collection
    put :favorite, on: :member
    get "added_prayers", on: :collection
    resources :prayers, only: :create
    resources :comments 
  end

  resources :groups do
    resources :invites 
    resources :prayers 
    get "my_groups", on: :collection
    get 'join', :on => :member
  end

  get 'invite/:token/verify' => 'invites#verify', as: :verify
  devise_for :users, :controllers => {:registrations => "users/registrations"}
end

  #   end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prayer
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 before_action :find_prayer
 before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
 before_action :comment_owner, only: [:destroy, :edit, :update]
 def create
 	@comment = @prayer.comments.create(params[:comment].permit(:content))
 	@comment.user_id = current_user.id
 	@comment.save

 	if @comment.save
 		redirect_to prayer_path(@prayer)
 	else
 		render 'new'
 	end
 end

 def destroy
 	@comment.destroy
 	redirect_to prayer_path(@prayer)
 end

 def edit

 end


 def update
 	if @comment.update(params[:comment].permit(:content))
 		redirect_to prayer_path(@prayer)
 	else
 		render 'edit'
 	end
 end

 private

 def find_prayer
 	@prayer = Prayer.find(params[:prayer_id])
 end

 def find_comment
 	@comment = @prayer.comments.find(params[:id])
 end

 def comment_owner
 	unless current_user.id == @comment.user_id
 		flash[:notice] = "You are not authorized"
 		redirect_to @prayer
 	end
 end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
 <p><strong><%= comment.user.name %></strong></p>
 <p><%= comment.content %></p>
 <% if current_user == comment.user %>
 	<%= link_to "Delete comment", [comment.prayer, comment], method: :delete %>
 	<%= link_to "Edit comment", edit_prayer_comment_path(comment.prayer, comment) %>
 <% end %>
<% end %>

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<%= form_for([@prayer, @prayer.comments.build]) do |f| %>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<%= form_for([@prayer, @comment]) do |f| %>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>