config/routes.rb
Rails.application.routes.draw do
  root to: 'groups#my_groups'

  resources :prayers do
    get "my_prayers", on: :collection
    put :favorite, on: :member
    get "added_prayers", on: :collection
    resources :prayers, only: :create
    resources :comments 
  end

  resources :groups do
    resources :invites 
    resources :prayers 
    get "my_groups", on: :collection
    get 'join', :on => :member
  end

  get 'invite/:token/verify' => 'invites#verify', as: :verify
  devise_for :users, :controllers => {:registrations => "users/registrations"}
end

  #   end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  belongs_to :user
  has_many :users, -> { distinct }, through: :memberships
  has_many :prayers, through: :prayer_groups
  has_many :prayer_groups
  has_many :invites
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

def index
	@groups = Group.all
end

def new
	@group = Group.new
end  

def edit
  @group = Group.find(params[:id])
end

def create
  @group = Group.new(group_params)
  @group.user = current_user
 		if @group.save
 			@group.users << current_user
			redirect_to my_groups_groups_path, notice: "New group created!"
    	else
      	render :new
    	end
end

def update
  @group = Group.find(params[:id])
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_prayers_path(@group), notice: 'Group name was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
end

 def join
	@group = Group.find(params[:id])
  if current_user.groups.include?(@group)
    redirect_to :back, notice: "You have already joined this group!"
  else
	 @group.users << current_user
 	  if @group.save
 		 redirect_to :back, notice: "You have joined this group!"
 	  else
        format.html { redirect_to(@group, :notice => 'Join error.') }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
 	  end
  end
 end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |format|
      format.html { redirect_to my_groups_groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def my_groups
    @groups = current_user.try(:groups)
  end


 private

   def group_params
      params.require(:group).permit(:groupname)
   end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
	<p> Group Name </p>
    <%= f.text_field :groupname %>
    <%= f.submit %>
<% end %>

app/views/groups/edit.html.erb
<h3>Update Group name</h3>

<%= render 'form' %>

<%= link_to 'Back', my_groups_groups_path %>

app/views/groups/index.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><a href="/groups/my_groups">Home</a></li>
  <li role="presentation"><a href="/prayers/my_prayers">My Prayer Requests</a></li>
  <li role="presentation"><a href="/prayers/added_prayers">My Prayer Items</a></li>
  <li role="presentation"><a href="/groups/my_groups">My Groups</a></li>
</ul>
<h3>Hello, <%= current_user.name %></h3>

<h3>All Groups</h3>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Date Posted</th>
      <th>Group Name</th>
      <th>Group Owner</th>
      <th>Group Users</th>
      <th>Prayers</th>
      <th colspan="1">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.created_at.strftime("%B %d %Y, %l:%M%P") %></td>
        <td><%= group.groupname %></td>
        <td><%= group.user.try(:name) %></td>
        <td><%= group.users.collect(&:name).join(', ') %></td>
        <td>
          <%= link_to 'View', group_prayers_path(group.id) %>
        </td>
        <td>
            <%= link_to 'Join', join_group_path(group) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/my_groups.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><a href="/groups/my_groups">Home</a></li>
  <li role="presentation"><a href="/prayers/my_prayers">My Prayer Requests</a></li>
  <li role="presentation"><a href="/prayers/added_prayers">My Prayer Items</a></li>
  <li role="presentation"><a href="/groups/my_groups">My Groups</a></li>
</ul>
<h3><%= current_user.name %>'s Groups</h3>
<p></p>
<%= link_to 'Create New Group', new_group_path, :class => "btn btn-primary" %>
<p></p>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Date Posted</th>
      <th>Group Name</th>
      <th>Group Owner</th>
      <th>Group Users</th>
      <th>Prayers</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.created_at.strftime("%B %d %Y, %l:%M%P") %></td>
        <td><%= group.groupname %></td>
        <td><%= group.user.try(:name) %></td>
        <td><%= group.users.collect(&:name).join(', ') %></td>
        <td>
          <%= link_to 'View', group_prayers_path(group.id) %>
        </td>
        <td>
            <% if group.user.try(:name) == current_user.name %>
            <%= link_to 'Invite', new_group_invite_path(group) %> |
            <%= link_to 'Edit', edit_group_path(group) %> | 
            <%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
            <%= link_to 'Invite', new_group_invite_path(group) %>
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
<% else %>
  <%= link_to('Login', new_user_session_path)  %>  
<% end %>

app/views/groups/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', my_groups_groups_path %>