config/routes.rb
Rails.application.routes.draw do
  root to: 'groups#my_groups'

  resources :prayers do
    get "my_prayers", on: :collection
    put :favorite, on: :member
    get "added_prayers", on: :collection
    resources :prayers, only: :create
    resources :comments 
  end

  resources :groups do
    resources :invites 
    resources :prayers 
    get "my_groups", on: :collection
    get 'join', :on => :member
  end

  get 'invite/:token/verify' => 'invites#verify', as: :verify
  devise_for :users, :controllers => {:registrations => "users/registrations"}
end

  #   end

app/models/prayer.rb
class Prayer < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :favorite_prayers
	has_many :favorited_by, through: :favorite_prayers, source: :user
	has_many :prayer_groups
	has_many :groups, through: :prayer_groups
	accepts_nested_attributes_for :prayer_groups, :allow_destroy => true
	validates :name, :presence => true
	validates :description, :presence => true
	validates :groups, :presence => true
end

app/controllers/prayers_controller.rb
class PrayersController < ApplicationController
  before_action :set_prayer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: :index 
  # GET /prayers
  # GET /prayers.json
  def index
    if params[:user_id].present?
      @prayers = User.find(params[:user_id]).prayers
    elsif params[:group_id].present?
      @group = Group.find(params[:group_id])
      @prayers = @group.prayers
    else
    @prayers = Prayer.all
    end
  end


  # GET /prayers/1
  # GET /prayers/1.json
  def show
    @comments = Comment.where(prayer_id: @prayer).order("created_at DESC")
  end

  # GET /prayers/new
  def new
    @prayer = Prayer.new
  end

  # GET /prayers/1/edit
  def edit
  end

  # POST /prayers
  # POST /prayers.json

  def my_prayers
    @prayers = current_user.prayers
  end


  def favorite
    @prayer = Prayer.find(params[:id])
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @prayer
      redirect_to :back, notice: "Prayer has been added!"

    elsif type == "unfavorite"
      current_user.favorites.delete(@prayer)
      redirect_to :back, notice: "Prayer has been removed"

    else 
      redirect_to :back, notice: "Nothing happened."
    end
  end
  
  def added_prayers
    @prayers = current_user.favorites
  end


  def create
    @prayer = current_user.prayers.new(prayer_params)

    respond_to do |format|
      if @prayer.save
        format.html { redirect_to @prayer, notice: 'Prayer was successfully created.' }
        format.json { render :show, status: :created, location: @prayer }
      else
        format.html { render :new }
        format.json { render json: @prayer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prayers/1
  # PATCH/PUT /prayers/1.json
  def update
    respond_to do |format|
      if @prayer.update(prayer_params)
        format.html { redirect_to @prayer, notice: 'Prayer was successfully updated.' }
        format.json { render :show, status: :ok, location: @prayer }
      else
        format.html { render :edit }
        format.json { render json: @prayer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prayers/1
  # DELETE /prayers/1.json
  def destroy
    @prayer.destroy
    respond_to do |format|
      format.html { redirect_to my_prayers_prayers_url, notice: 'Prayer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prayer
      @prayer = Prayer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prayer_params
      params.require(:prayer).permit(:name, :description, :category, :pray, :status, group_ids:[])
    end
end

app/helpers/prayers_helper.rb
module PrayersHelper
end

app/views/prayers/_form.html.erb
<%= form_for(@prayer) do |f| %>
  <% if @prayer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prayer.errors.count, "error") %> prohibited this prayer from being saved:</h2>

      <ul>
      <% @prayer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :Answered %><br>
    <%= f.check_box :status %>
  </div>

  <div class="field">
    <%= f.label :Add_to_which_group %><br>
    <%= collection_check_boxes(:prayer, :group_ids, current_user.groups, :id, :groupname) %>
  </div>

  <div class="actions">
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
    Add/Update Prayer
    <% end %>
  </div>
<% end %>

app/views/prayers/added_prayers.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><a href="/groups/my_groups">Home</a></li>
  <li role="presentation"><a href="/prayers/my_prayers">My Prayer Requests</a></li>
  <li role="presentation"><a href="/prayers/added_prayers">My Prayer Items</a></li>
  <li role="presentation"><a href="/groups/my_groups">My Groups</a></li>
</ul>

<h3>My Prayer Items</h3>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Lister</th>
      <th>Description</th>
      <th>Answered</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @prayers.each do |prayer| %>
      <tr>
        <td><%= prayer.name %></td>
        <td><%= prayer.user.name %></td>
        <td><%= prayer.description %></td>
        <td>
          <% if prayer.status? %>
          <%= 'Yes' %>
          <% else %>
          <%= 'Not yet' %>
          <% end %>
          </td>
        <td>
          <% if prayer.user.name == current_user.name %>
            <%= link_to 'Edit', edit_prayer_path(prayer) %>
            <%= link_to 'Delete', prayer, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
            <%= link_to 'Show', prayer %>
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
<% else %>
  <%= link_to('Login', new_user_session_path)  %>  
<% end %>

app/views/prayers/edit.html.erb
<h1>Update Prayer</h1>

<%= render 'form' %>

<%= link_to 'Show', @prayer %> |
<%= link_to 'Back', my_prayers_prayers_path %>

app/views/prayers/index.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><a href="/groups/my_groups">Home</a></li>
  <li role="presentation"><a href="/prayers/my_prayers">My Prayer Requests</a></li>
  <li role="presentation"><a href="/prayers/added_prayers">My Prayer Items</a></li>
  <li role="presentation"><a href="/groups/my_groups">My Groups</a></li>
</ul>

<h3>Hello, <%= current_user.name %></h3>

<h3>Prayers for <%= @group.groupname %></h3>
<p></p>
<%= link_to 'Add New Prayer', new_prayer_path, :class => "btn btn-primary" %>
<p></p>


<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Date Posted</th>
      <th>Title</th>
      <th>Lister</th>
      <th>Description</th>
      <th>Answered Status</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @prayers.each do |prayer| %>
      <tr>
        <td><%= prayer.created_at.strftime("%B %d %Y, %l:%M%P") %></td>
        <td><%= prayer.name %></td>
        <td><%= prayer.user.name %></td>
        <td><%= prayer.description %></td>
        <td>
          <% if prayer.status? %>
          <%= 'Yes' %>
          <% else %>
          <%= 'Not yet' %>
          <% end %>
        </td>
        <td>
          <% if prayer.user.name == current_user.name %>
            <%= link_to 'Edit', edit_prayer_path(prayer) %>
            <%= link_to 'Delete', my_prayers_prayers_path, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
            <%= link_to 'Show', prayer %>
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
<% else %>
  <%= link_to('Login', new_user_session_path)  %>  
<% end %>

app/views/prayers/my_prayers.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><a href="/groups/my_groups">Home</a></li>
  <li role="presentation"><a href="/prayers/my_prayers">My Prayer Requests</a></li>
  <li role="presentation"><a href="/prayers/added_prayers">My Prayer Items</a></li>
  <li role="presentation"><a href="/groups/my_groups">My Groups</a></li>
</ul>

<h3>My Prayer Requests</h3>

<p></p>
<%= link_to 'Add New Prayer', new_prayer_path, :class => "btn btn-primary" %>
<p></p>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Lister</th>
      <th>Description</th>
      <th>Group</th>
      <th>Answered</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @prayers.each do |prayer| %>
      <tr>
        <td><%= prayer.name %></td>
        <td><%= prayer.user.name %></td>
        <td><%= prayer.description %></td>
        <td><%= prayer.groups.collect(&:groupname).join(', ') %></td>
        <td>
          <% if prayer.status? %>
          <%= 'Yes' %>
          <% else %>
          <%= 'Not yet' %>
          <% end %>
        </td>
        <td>
          <% if prayer.user.name == current_user.name %>
            <%= link_to 'Edit', edit_prayer_path(prayer) %>
            <%= link_to 'Delete', prayer, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
            <%= link_to 'Show', prayer %>
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
<% else %>
  <%= link_to('Login', new_user_session_path)  %>  
<% end %>

app/views/prayers/new.html.erb
<h1>New Prayer</h1>

<%= render 'form' %>

<%= link_to 'Back', my_prayers_prayers_path %>

app/views/prayers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @prayer.name %>
</p>

<p>
  <strong>Lister:</strong>
  <%= @prayer.user.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @prayer.description %>
</p>

<p>
  <strong>Answered status:</strong>
  <% if @prayer.status? %>
    <%= 'Yes' %>
  <% else %>
    <%= 'Not yet' %>
  <% end %>
</p>

<% if @prayer.user.name != current_user.name %>
    <%= form_for [@prayer] do |f| %>
  <p>
    <% if !current_user.favorites.exists?(@prayer) %>
    <strong>Add to my prayer list? </strong>
      <%= link_to "Add",   favorite_prayer_path(@prayer, type: "favorite"), :class => "btn btn-primary", method: :put %>
    <% else %>
    <strong>Remove from my prayer list? </strong>
    <%= link_to 'Remove', favorite_prayer_path(@prayer, type: "unfavorite"), :class => "btn btn-primary", method: :put %>
    <% end %>
  </p>
  <% end %> 
<% else %>                 
<% end %>

<%= render 'comments/comment' %>

<%= link_to 'Edit', edit_prayer_path(@prayer) %> |
<%= link_to 'Back', added_prayers_prayers_path %>